dockers: python3-lxml is required
```
[  1%] Generate with documentation for pyhpp/pinocchio/urdf/bindings.cc
Traceback (most recent call last):
  File "../../doc/configure.py", line 76, in <module>
    from doxygen_xml_parser import Index
  File "/workspace/src/hpp-python/doc/doxygen_xml_parser.py", line 2, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'